#!/bin/bash

docker run --rm -d \
  -v /etc/localtime:/etc/localtime:ro \
  -v /tmp/.X11-unix:/tmp/.X11-unix \
  -e DISPLAY=unix$DISPLAY \
  -v $HOME/Documents:/root/Documents \
  -e GDK_SCALE \
  -e GDK_DPI_SCALE \
  --name libreoffice \
  tbalthazar/libreoffice
