#!/bin/bash

docker run --rm \
  -p 5432:5432 \
  -v /tmp/pg-vol:/var/lib/postgresql/data \
  -v /tmp/walg:/tmp/walg \
  -e POSTGRES_HOST_AUTH_METHOD=trust \
  -e WALG_FILE_PREFIX=/tmp/walg \
  --name pg-restore \
  tbalthazar/pg-wal-g \
  /wal-g/restore.sh


docker run --rm \
  -u postgres \
  -p 5432:5432 \
  -v /tmp/pg-vol:/var/lib/postgresql/data \
  -v /tmp/walg:/tmp/walg \
  -e POSTGRES_HOST_AUTH_METHOD=trust \
  -e WALG_FILE_PREFIX=/tmp/walg \
  --name pg \
  tbalthazar/pg-wal-g \
  -c restore_command='wal-g wal-fetch %f %p' \
  -c recovery_end_command='su -p postgres -c "pg_ctl stop"'

---

docker run --rm \
  -u 3001:3001 \
  -p 5432:5432 \
  -v /tmp/walg:/tmp/walg \
  -v /mnt/traefik01-volume/nextcloud/db/var/lib/postgresql/data:/var/lib/postgresql/data \
  -v /etc/passwd:/etc/passwd:ro \
  --env-file db.env \
  --name pg-restore \
  tbalthazar/pg-wal-g \
  /wal-g/restore.sh

docker run --rm \
  -u 3001:3001 \
  -p 5432:5432 \
  -v /mnt/traefik01-volume/nextcloud/db/var/lib/postgresql/data:/var/lib/postgresql/data \
  -v /etc/passwd:/etc/passwd:ro \
  -v /tmp/walg:/tmp/walg \
  --env-file db.env \
  --name pg \
  tbalthazar/pg-wal-g \
  -c restore_command='wal-g wal-fetch %f %p' \
  -c recovery_end_command='pg_ctl stop'
