#!/bin/bash

# usage: pdftk ~/path-to/file.pdf 10-12

basedir=$(dirname $1)
filename=$(basename $1)
name="${filename%%.*}"
ext="${filename#*.}"
pages=$2
destfilename="$name-$pages-$ext"
# echo $basedir $filename $pages $name $ext $destfilename

docker run --rm -it \
  -v $basedir:/workdir \
  tbalthazar/pdftk \
  /workdir/$filename \
  cat $pages \
  output /workdir/$destfilename
