FROM ubuntu:latest
LABEL maintainer "Thomas Balthazar <thomas@balthazar.info>"

RUN apt-get update && apt-get install -y \
  adwaita-icon-theme-full \
  thunar \
	--no-install-recommends \
  && rm -rf /var/lib/apt/lists/*

ENV USER tb
RUN useradd --create-home --home-dir /home/$USER $USER
USER $USER

ENTRYPOINT [ "thunar" ]
