name: Build pg-wal-g image

on:
  push:
    branches: [ main ]
    paths:
    - "pg-wal-g/*"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      WALG_VERSION: v0.2.19
    steps:
      - uses: actions/checkout@v2

      - name: Build the Docker image
        run: docker build -t tbalthazar/pg-wal-g:latest pg-wal-g --no-cache --build-arg WALG_VERSION=$WALG_VERSION
        
      - name: Log in to registry
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "tbalthazar" --password-stdin
        
      - name: Push image
        run: docker push tbalthazar/pg-wal-g:latest